openapi: 3.0.3
info:
  version: 1.0.0
  title: Sample Books API
  description: An example API for managing books
servers:
  - url: http://localhost:3000/api/v1
paths:
  /books:
    get:
      summary: Get a list of books
      description: Retrieve a paginated list of books from the server
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination (default is 1)
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 1
      responses:
        '200':
          description: A successful response with a list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      description: The ID of the book
                    title:
                      type: string
                      description: The title of the book
                    data:
                      type: object
                      properties:
                        info:
                          type: string
                          description: Some kind of information about the book
                      description: Additional data about the book
                    author_id:
                      type: integer
                      format: int64
                      description: The ID of the book's author
                    created_at:
                      type: string
                      format: date-time
                      description: The date and time the book was created
                    updated_at:
                      type: string
                      format: date-time
                      description: The date and time the book was last updated
  /books/{id}:
    get:
      summary: Get a specific book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A successful response with the book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: The requested book was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    put:
      summary: Update a book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBook'
      responses:
        '200':
          description: The book was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: The requested book was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      summary: Delete a book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The book was deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        data:
          type: object
          properties:
            info:
              type: string
        author_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewBook:
      type: object
      required:
        - title
        - author_id
      properties:
        title:
          type: string
        author_id:
          type: integer
          format: int64
        data:
          type: object
          properties:
            info:
              type: string

    UpdateBook:
      type: object
      properties:
        title:
          type: string
        author_id:
          type: integer
          format: int64
        data:
          type: object
          properties:
            info:
              type: string